### ISSUE TITLE
"import luma.emulator.device" fails

### ISSUE THREAD

**Issue by leonidlezner** [rm-hull/luma.emulator#19]
Hello Richard,

it seems that serial.py is missing in the master branch in luma.core (the file is present in the develop branch). Because of that following import fails:

```
ModuleNotFoundError: No module named 'luma.emulator.devices'
>>> import luma.emulator.device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leonidlezner/Envs/ledmatrix/lib/python3.6/site-packages/luma/emulator/device.py", line 20, in <module>
    from luma.core.serial import noop
ModuleNotFoundError: No module named 'luma.core.serial'
>>> import luma.core.serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'luma.core.serial'

```

**Comment by thijstriemstra** [comment]
It should import `luma.core.interface.serial.noop` instead (since v1.0), so you're right, this is a bug (and I'm surprised this wasn't caught by unit tests before).

See https://github.com/rm-hull/luma.core/blob/master/luma/core/interface/serial.py

**Comment by thijstriemstra** [comment]
Tests are actually catching the error, I guess they just haven't been run since luma.core 1.0:

```
____________________________________ ERROR collecting tests/test_gifanim.py _____________________________________
ImportError while importing test module '/home/thijs/luma.emulator/tests/test_gifanim.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_gifanim.py:16: in <module>
    from luma.emulator.device import gifanim
luma/emulator/device.py:20: in <module>
    from luma.core.serial import noop
E   ImportError: No module named serial
```

**Comment by rm-hull** [comment]
I pushed v0.2.5 of luma.emulator to pypi with @thijstriemstra's fix
