### ISSUE TITLE
device api documentation is empty

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.emulator#29]
See https://luma-emulator.readthedocs.io/en/latest/api-documentation.html#module-luma.emulator.device

**Comment by rm-hull** [comment]
Fails for me locally with sphinx 1.5.3, works locally with sphinx 1.6.5.
Might try bumping version on a branch

**Comment by thijstriemstra** [comment]
> Fails for me locally

With what error?

**Comment by rm-hull** [comment]
It was similar to the warnings in http://readthedocs.org/projects/luma-emulator/builds/6221611/ (can you see this?), copied below:

```
python /home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/envs/stable/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.5.6
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://luma-core.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://pillow.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [ 25%] api-documentation
reading sources... [ 50%] index
reading sources... [ 75%] install
reading sources... [100%] intro

/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/doc/api-documentation.rst:8: WARNING: Could not import class or module u'luma.core.device' specified for inheritance diagram
/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/doc/api-documentation.rst:12: WARNING: autodoc: failed to import module u'luma.emulator.device'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/envs/stable/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 560, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/luma/emulator/device.py", line 19, in <module>
    from luma.core.device import device
ImportError: No module named core.device
/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/doc/index.rst:None: WARNING: nonlocal image URI found: https://travis-ci.org/rm-hull/luma.emulator.svg?branch=master
/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/doc/index.rst:None: WARNING: nonlocal image URI found: https://coveralls.io/repos/github/rm-hull/luma.emulator/badge.svg?branch=master
/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/doc/index.rst:10: WARNING: nonlocal image URI found: https://img.shields.io/maintenance/yes/2017.svg?maxAge=2592000
/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/doc/index.rst:None: WARNING: nonlocal image URI found: https://img.shields.io/pypi/pyversions/luma.emulator.svg
/home/docs/checkouts/readthedocs.org/user_builds/luma-emulator/checkouts/stable/doc/index.rst:None: WARNING: nonlocal image URI found: https://img.shields.io/pypi/v/luma.emulator.svg
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 25%] api-documentation
writing output... [ 50%] index
writing output... [ 75%] install
writing output... [100%] intro

generating indices... genindex py-modindex
highlighting module code... [100%] luma.emulator.render

writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
done
copying readthedocs static files... done
copying searchtools... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 8 warnings.
```

**Comment by thijstriemstra** [comment]
It should be fixed by setting this to true: https://github.com/rm-hull/luma.emulator/blob/master/.readthedocs.yml#L3

**Comment by rm-hull** [comment]
Yup, that fixes it:

![screenshot from 2017-11-08 20-27-29](https://user-images.githubusercontent.com/1915543/32572725-69a2006e-c4c3-11e7-9edb-9d9cf6098085.png)
